apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  # labels:
  #   app: backend
spec:
  selector:
    # app.kubernetes.io/name: backend
    app: frontend-pod
    #app.kubernetes.io/name: backend-deployment
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
