# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
# spec:
#   type: NodePort
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
#       # nodePort: 8080

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
